services:
  - type: web
    name: jsproxy
    env: static
    branch: gh-pages
    buildCommand: "cp assets/index_v3.html index.html"
    staticPublishPath: .
    headers:
      - path: /*
        name: Service-Worker-Allowed
        value: /
      - path: /*
        name: Cache-Control
        value: no-store
    routes:
      - type: rewrite
        source: /404
        destination: /404.html
      - type: rewrite
        source: /*
        destination: /index.html
